export const STEPS = [
  {
    id: "welcome",
    type: "modal",
    page: "/",
  },
  {
    id: "go-brand-settings",
    type: "tooltip",
    selector: '[data-onboarding="brand-settings-link"]',
    position: "right",
    milestone: 1,
    // No page constraint — sidebar link is visible on every page
    stepLabel: "Step 1 of 3",
    title: "First, define your brand",
    body: "Tell the AI who you are — your brand name, audience, and voice. This shapes every post it writes.",
    cta: "Go to Brand Settings →",
    advanceTo: "/brand",
  },
  {
    id: "create-brand",
    type: "tooltip",
    selector: '[data-onboarding="new-brand-btn"]',
    position: "bottom",
    milestone: 1,
    page: "/brand",
    stepLabel: "Step 1 of 3",
    title: "Create your first brand",
    body: "Click here to add a brand profile. Just a name and a few details — you can always edit it later.",
    cta: "Create Profile",
    advanceOn: "brand-created",
  },
  {
    id: "go-api-keys",
    type: "tooltip",
    selector: '[data-onboarding="api-keys-link"]',
    position: "right",
    milestone: 2,
    // No page constraint — sidebar link is visible on every page
    stepLabel: "Step 2 of 3",
    title: "Now connect an AI provider",
    body: "Add an API key from any LLM provider to power generation. Or use the Mock provider with a dummy key to try it out first.",
    cta: "Go to API Keys →",
    advanceTo: "/settings",
  },
  {
    id: "add-api-key",
    type: "banner",
    milestone: 2,
    page: "/settings",
    advanceOn: "default-key-set",
  },
  {
    id: "go-generate",
    type: "tooltip",
    selector: '[data-onboarding="generate-link"]',
    position: "right",
    milestone: 3,
    // No page constraint — sidebar link is visible on every page
    stepLabel: "Step 3 of 3",
    title: "Time to create your first post",
    body: "Everything's set up. Let's generate some AI-powered social media content for your brand.",
    cta: "Go to Generate →",
    advanceTo: "/generate",
  },
  {
    id: "generate-banner",
    type: "banner",
    milestone: 3,
    page: "/generate",
    advanceOn: "generation-complete",
  },
];
